---
title: "Tidy Data"
output: github_document
Date: 10/06/2023
---
Focus on readr.
```{r setup}
library(tidyverse)
#Have `tidyr`, `dplyr`, `haven`, `readr`
```

## `pivot_longer` function

Import and load the PULSE data
```{r}
pulse_data =
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names()
```

Wide format to long format ...

```{r}
pulse_data_tidy =
  pulse_data %>% 
  pivot_longer(
    bdi_score_bl :bdi_score_12m, #from bl to 12m
    names_to ="visit", #create new variable from existing
    names_prefix = "bdi_score_", #remove the matched start of each variable name
    values_to = "bdi"
  )
``` 

## Put everything into a single chunk ##

**Rewrite, combine, and extend (to add a mutate)**

```{r}
pulse_data =
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names() %>%
  pivot_longer(
    bdi_score_bl :bdi_score_12m, #from bl to 12m
    names_to ="visit", #create new variable from existing
    names_prefix = "bdi_score_", #remove the matched start of each variable name
    values_to = "bdi"
  ) %>% 
  relocate(id, visit) %>% #select to have `id`, `visit` in the first
  mutate(visit = recode(visit, "bl" = "00m"))
```

DONE with `pivot_longer` example


## `pivot_wider` function

Make up some data (using `tibble` function)

```{r}
analysis_result =
  tibble(
    group = c("treatment", "treatment", "placebo", "placebo"),
    time = c("pre", "post", "pre", "post"),
    mean = c(4, 8, 3.5, 4) #Add some observational time
  )

analysis_result %>% 
  pivot_wider(
    names_from = "time",
    values_from = "mean"
  )
```

```{r}

```


